#ifndef IMAGE_RENAME_METADATA_SERVICE_HPP
#define IMAGE_RENAME_METADATA_SERVICE_HPP

#include <chrono>
#include <filesystem>
#include <optional>
#include <string>

struct sqlite3;

/**
 * @brief Enriches image rename suggestions using EXIF date + reverse-geocoded place.
 *
 * Metadata sources:
 * - JPEG APP1 EXIF
 * - TIFF native EXIF
 * - PNG eXIf chunk
 * - HEIC/HEIF via exiftool fallback (when available in PATH)
 */
class ImageRenameMetadataService {
public:
    /**
     * @brief Creates a metadata enrichment service rooted in the given config directory.
     *
     * The directory is used to store the local reverse-geocode cache database.
     *
     * @param config_dir Base configuration directory for metadata cache files.
     */
    explicit ImageRenameMetadataService(std::string config_dir);
    /**
     * @brief Destroys the service and releases any open cache database resources.
     */
    ~ImageRenameMetadataService();

    ImageRenameMetadataService(const ImageRenameMetadataService&) = delete;
    ImageRenameMetadataService& operator=(const ImageRenameMetadataService&) = delete;

    /**
     * @brief Adds metadata prefixes to a suggested image filename when available.
     *
     * Prefix order is date first, then place, e.g. `2014-03-10_venice_black_ducks.jpg`.
     * If EXIF metadata is missing or place lookup cannot be done, the original
     * suggestion is returned unchanged.
     *
     * @param image_path Absolute or relative image file path.
     * @param suggested_name Suggested filename generated by image analysis.
     * @return Suggested filename with metadata prefixes when available.
     */
    std::string enrich_suggested_name(const std::filesystem::path& image_path,
                                      const std::string& suggested_name);

    /**
     * @brief Extracts the normalized capture date (`YYYY-MM-DD`) from image metadata.
     *
     * Returns `std::nullopt` when no supported metadata date is available.
     *
     * @param image_path Absolute or relative image file path.
     * @return Normalized capture date, or `std::nullopt` if unavailable.
     */
    std::optional<std::string> extract_capture_date(
        const std::filesystem::path& image_path) const;

    /**
     * @brief Utility used by tests and callers to compose prefixed filenames.
     *
     * @param suggested_name Base suggested filename.
     * @param date_prefix Optional date prefix (typically `YYYY-MM-DD`).
     * @param place_prefix Optional place prefix.
     * @return Filename prefixed with available metadata components.
     */
    static std::string apply_prefix_to_filename(const std::string& suggested_name,
                                                const std::optional<std::string>& date_prefix,
                                                const std::optional<std::string>& place_prefix);

private:
    struct ExifMetadata {
        std::optional<std::string> capture_date;
        std::optional<double> latitude;
        std::optional<double> longitude;
    };

    struct CacheLookup {
        bool found{false};
        std::optional<std::string> place;
    };

    struct ReverseGeocodeResult {
        bool success{false};
        std::optional<std::string> place;
    };

    /**
     * @brief Opens or creates the reverse-geocode cache database.
     * @return True when the cache database is available for use.
     */
    bool open_cache_db();
    /**
     * @brief Extracts supported EXIF metadata fields from an image file.
     * @param image_path Absolute or relative image file path.
     * @return Parsed metadata fields used for date/place prefixing.
     */
    ExifMetadata extract_exif_metadata(const std::filesystem::path& image_path) const;
    /**
     * @brief Resolves a place prefix from GPS coordinates using cache and reverse geocoding.
     * @param latitude GPS latitude in decimal degrees.
     * @param longitude GPS longitude in decimal degrees.
     * @return Slugified place prefix, or `std::nullopt` when unavailable.
     */
    std::optional<std::string> resolve_place_prefix(double latitude, double longitude);
    /**
     * @brief Looks up a cached place prefix by coordinate keys.
     * @param lat_key Normalized latitude cache key.
     * @param lon_key Normalized longitude cache key.
     * @return Cache lookup result indicating hit/miss and optional place value.
     */
    CacheLookup lookup_cache(const std::string& lat_key, const std::string& lon_key) const;
    /**
     * @brief Inserts or updates a cached place prefix for coordinate keys.
     * @param lat_key Normalized latitude cache key.
     * @param lon_key Normalized longitude cache key.
     * @param place Optional place prefix to store.
     */
    void upsert_cache(const std::string& lat_key,
                      const std::string& lon_key,
                      const std::optional<std::string>& place) const;
    /**
     * @brief Performs reverse geocoding for GPS coordinates.
     * @param latitude GPS latitude in decimal degrees.
     * @param longitude GPS longitude in decimal degrees.
     * @return Reverse-geocode result with success flag and optional place prefix.
     */
    ReverseGeocodeResult reverse_geocode(double latitude, double longitude);
    /**
     * @brief Checks whether the network is available for reverse geocoding.
     * @return True when online requests can be attempted.
     */
    bool network_available();

    /**
     * @brief Converts arbitrary text into a filesystem-safe lowercase slug.
     * @param value Input text.
     * @return Sanitized slug string.
     */
    static std::string slugify(const std::string& value);
    /**
     * @brief Normalizes EXIF date values to `YYYY-MM-DD`.
     * @param value Raw EXIF date text.
     * @return Normalized date, or `std::nullopt` if parsing fails.
     */
    static std::optional<std::string> normalize_exif_date(const std::string& value);
    /**
     * @brief Formats a floating-point coordinate into a stable cache key.
     * @param value Coordinate value in decimal degrees.
     * @return Normalized coordinate key string.
     */
    static std::string format_coord_key(double value);

    std::string config_dir_;
    sqlite3* cache_db_{nullptr};
    std::chrono::steady_clock::time_point last_geocode_request_{};
    bool network_checked_{false};
    bool network_available_{false};
};

#endif // IMAGE_RENAME_METADATA_SERVICE_HPP
