#!/bin/bash

echo "=============================================="
echo "    AI File Sorter - Project Information     "
echo "=============================================="
echo ""
echo "This is a C++ Qt6 desktop GUI application that"
echo "uses local LLMs (llama.cpp) for file categorization."
echo ""
echo "BUILD REQUIREMENTS:"
echo "  - C++20 compiler (g++ or clang++)"
echo "  - Qt6 with OpenGL support"
echo "  - llama.cpp (built from source)"
echo "  - Native libraries: curl, sqlite3, openssl, fmt, spdlog"
echo ""
echo "REPLIT ENVIRONMENT LIMITATION:"
echo "  This project cannot be fully built in Replit due to:"
echo "  - Path length restrictions with nix packages"
echo "  - Missing git submodule support"
echo "  - Desktop GUI (Qt6/OpenGL) requirements"
echo ""
echo "FOR LOCAL DEVELOPMENT:"
echo ""
echo "Linux:"
echo "  sudo apt install build-essential cmake qt6-base-dev \\"
echo "    libcurl4-openssl-dev libjsoncpp-dev libsqlite3-dev \\"
echo "    libssl-dev libfmt-dev libspdlog-dev"
echo "  git submodule update --init --recursive"
echo "  ./app/scripts/build_llama_linux.sh cuda=off vulkan=off"
echo "  cd app && make -j4"
echo ""
echo "macOS:"
echo "  brew install qt curl jsoncpp sqlite openssl fmt spdlog cmake"
echo "  git submodule update --init --recursive"
echo "  ./app/scripts/build_llama_macos.sh"
echo "  cd app && make -j4"
echo ""
echo "See README.md for complete build instructions."
echo ""
echo "=============================================="
echo "         Project Structure Overview          "
echo "=============================================="
find . -maxdepth 2 -type d | grep -v ".git" | head -20
echo ""
echo "Source files in app/lib/:"
ls -la app/lib/*.cpp 2>/dev/null | wc -l
echo " C++ source files"
echo ""
echo "Header files in app/include/:"
ls -la app/include/*.hpp 2>/dev/null | wc -l
echo " header files"
